# permissions for end users to edit demo01s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demo01-editor-role
rules:
- apiGroups:
  - test-hjy.demo01
  resources:
  - demo01s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test-hjy.demo01
  resources:
  - demo01s/status
  verbs:
  - get
