
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - test-hjy.demo01
  resources:
  - demo01s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test-hjy.demo01
  resources:
  - demo01s/finalizers
  verbs:
  - update
- apiGroups:
  - test-hjy.demo01
  resources:
  - demo01s/status
  verbs:
  - get
  - patch
  - update
