apiVersion: hjy-dev.my.domain/v1
kind: Nginx
metadata:
  name: nginx-sample-2
spec:
  # Add fields here
  #foo: bar
  size: 2
  image: nginx:1.7.9
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
status:
 
  

  

        
     
      
